# Site settings
title: 
header-img: img/home-bg.png
email: josh.rowley@flatironschool.com
copyright_name: joshrowley
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: joshrowley
github_username:  joshrowley
learn_profile: joshrowley
email_username: josh.rowley@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
